# CDoc/gdjs
#
# This work is licensed under the Creative 
# Commons Attribution-ShareAlike 3.0 Unported License. 
# To view a copy of this license, visit 
# http://creativecommons.org/licenses/by-sa/3.0/
# or send a letter to Creative Commons, 444 Castro Street, 
# Suite 900, Mountain View, California, 94041, USA.

#
# Use these definitions to configure/extend your output.
#

use strict;
use warnings;

my $CSS = <<CSS;
body
{
    margin: 30px;
    font-family: Verdana;
}

#footer
{
    text-align: center;
    font-size: 80%;
}

table tr td
{
    border: 1px solid #000;
    padding: 5px;
}

td.property
{
    font-weight: bold;
}
CSS

my $sourcefile = <<SOURCEFILE;
<!-- Documentation generated by CDoc ( https://github.com/guipn/CDoc/ ) -->
<html>
<head>
    <title><ProjectName> Documentation: <FileName></title>
    <link rel="stylesheet" type="text/css" href="style.css"></link>
</head>
<body>
    <h1><a href="index.htm"><ProjectName></a>: <FileName></h1>
    <FileIntroduction>
    <IncSection>
    <DefSection>
    <FunSection>
    <div id="footer"><a href="<ProjectURL>"><ProjectName></a>, version <ProjectVersion>, by <a href="<AuthorshipURL>"><Authorship></a></div>
</body>
</html>
SOURCEFILE

my $summaryline = <<SUMMARYLINE;
    <a href="#<FunctionName>"><h3><FunctionName></h3></a> <ShortDescription> <br/>
SUMMARYLINE

my $prototype = <<PROTOTYPE;
    <h2><a name="<FunctionName>"><FunctionPrototype></h2>
    <FunctionDescription><ReturnsDescription>
    <p/>
    <br/>
    <br/>
PROTOTYPE

my $index = <<INDEX;
<!-- Documentation generated by CDoc ( https://github.com/guipn/CDoc/ ) -->
<html>
<head>
    <title><ProjectName> Documentation Index</title>
    <link rel="stylesheet" type="text/css" href="style.css"></link>
</head>
<body>
    <h1><ProjectName>: Documentation Index</h1>
    <Introduction>
    <p/>
    <IndexLines>
    <div id="footer"><a href="<ProjectURL>"><ProjectName></a>, version <ProjectVersion>, by <a href="<AuthorshipURL>"><Authorship></a></div>
</body>
</html>
INDEX

my $indexline = <<INDEXLINE;
    <a href="<FileName>.htm"><FileName></a><br/>
INDEXLINE


my $includeline = <<INCLUDELINE;
<em><IncludedFile></em><br/>
INCLUDELINE


my $defineline = <<DEFINELINE;
    <Macro><br/>
DEFINELINE


my $defsection = <<DEFSECTION;
<h2>Definitions</h2>
<Definitions>
<br/>
<br/>
DEFSECTION

my $incsection = <<INCSECTION;
<hr/>
    <h2>Files included</h2>
    <Inclusions>
    <br/>
    <br/>
INCSECTION

my $funsection = <<FUNSECTION;
<h2>Function Summary</h2>
    <SummaryLines>
    <p/>
    <hr/>
    <Prototypes>
FUNSECTION

my $fileintroduction = <<FILEINTRODUCTION;
<h2>Introduction</h2>
<FIntroText>
<p/>
FILEINTRODUCTION


sub getfunsection
{
    return $funsection;
}

sub getfileintroduction
{
    return $fileintroduction;
}

sub getincsection
{
    return $incsection;
}

sub getdefsection
{
    return $defsection;
}

sub getCSS
{
    return $CSS;	    
}

sub getsourcefile
{
    return $sourcefile;
}

sub getsummaryline
{
    return $summaryline;
}

sub getindexline
{
    return $indexline;
}

sub getindex
{
    return $index;
}

sub getprototype
{
    return $prototype;
}

sub getincludeline
{
    return $includeline;
}

sub getdefineline
{
    return $defineline;
}

1;
